/**
 * Writes the first events of every canonical trace to a committed reference.
 *
 * This is what makes a port's trace generator checkable. The Python and C
 * implementations regenerate the same prefix from the same seed and compare
 * event for event; if a port consumes a different
 * number of random draws, or sums its Zipf weights in a different order, the
 * sequences diverge and the parity test says exactly where.
 *
 * One file per domain, because domains do not share an event shape: a cache
 * event is a key, and a rate-limiter event is a time and a key. Each domain
 * registers an emitter below rather than the writer trying to be generic over
 * something that is genuinely different.
 *
 * Usage: pnpm tsx packages/core/scripts/dump-trace-prefix.ts
 */

import { writeFileSync } from "node:fs";
import { CACHE_TRACES, generateCacheTrace } from "../src/domains/cache/traces";
import {
  RATE_LIMITER_TRACES,
  generateRateLimiterTrace,
} from "../src/domains/rate-limiter/traces";
import { RETRY_TRACES, generateRetryTrace } from "../src/domains/retry/traces";
import {
  KV_CACHE_TRACES,
  float32Bits,
  generateKvCacheTrace,
  hashKvCacheTrace,
} from "../src/domains/kv-cache/traces";

/** How many events of each trace to record. */
const PREFIX_LENGTH = 10_000;

const NOTE =
  "Generated by packages/core/scripts/dump-trace-prefix.ts. The first events of each canonical trace, used by the Python and C parity tests. Do not edit by hand.";

interface Domain {
  /** Directory name under `src/domains/`, and the `domain` field in the file. */
  name: string;
  /** Trace ids, in the order they should appear. */
  ids: string[];
  /**
   * The body of the `traces` object: one entry per id, already serialized.
   *
   * Number arrays are written on one line each. Pretty-printing 40,000 numbers
   * would produce a 40,000-line file for no benefit: this is a machine-checked
   * fixture, and a per-trace line means a diff shows which trace changed.
   */
  entries(): string[];
}

const DOMAINS: Domain[] = [
  {
    name: "cache",
    ids: Object.keys(CACHE_TRACES),
    entries(): string[] {
      return this.ids.map((id, index) => {
        const prefix = Array.from(generateCacheTrace(id, PREFIX_LENGTH));
        const comma = index === this.ids.length - 1 ? "" : ",";
        return `    ${JSON.stringify(id)}: [${prefix.join(",")}]${comma}`;
      });
    },
  },
  {
    name: "rate-limiter",
    ids: Object.keys(RATE_LIMITER_TRACES),
    entries(): string[] {
      const lines: string[] = [];
      this.ids.forEach((id, index) => {
        // Two of these traces are shorter than the prefix length — an arrival
        // is the outcome of a Bernoulli trial, not a step of the loop — so the
        // reference records however many exist.
        const trace = generateRateLimiterTrace(id, PREFIX_LENGTH);
        const comma = index === this.ids.length - 1 ? "" : ",";
        lines.push(
          `    ${JSON.stringify(id)}: {`,
          `      "times": [${Array.from(trace.times).join(",")}],`,
          `      "keys": [${Array.from(trace.keys).join(",")}]`,
          `    }${comma}`,
        );
      });
      return lines;
    },
  },
  {
    name: "retry",
    ids: Object.keys(RETRY_TRACES),
    entries(): string[] {
      // One number per episode: the outage duration. Same shape as the cache's
      // flat array, because a retry episode's identity is a single draw.
      return this.ids.map((id, index) => {
        const outages = Array.from(generateRetryTrace(id, PREFIX_LENGTH));
        const comma = index === this.ids.length - 1 ? "" : ",";
        return `    ${JSON.stringify(id)}: [${outages.join(",")}]${comma}`;
      });
    },
  },
  {
    name: "kv-cache",
    ids: Object.keys(KV_CACHE_TRACES),
    entries(): string[] {
      const lines: string[] = [];
      this.ids.forEach((id, index) => {
        // Float32 *bit patterns*, not values: two floats that print alike can
        // differ in the last place, and for a generator whose whole job is
        // reproducibility that difference is the bug.
        const firstSteps: string[] = [];
        let step = 0;
        for (const weights of generateKvCacheTrace(id, KV_CACHE_PREFIX_STEPS)) {
          step += 1;
          const bits = Array.from(weights, (weight) => float32Bits(weight));
          const comma = step === KV_CACHE_PREFIX_STEPS ? "" : ",";
          firstSteps.push(`        [${bits.join(",")}]${comma}`);
        }

        const comma = index === this.ids.length - 1 ? "" : ",";
        lines.push(
          `    ${JSON.stringify(id)}: {`,
          `      "steps": ${KV_CACHE_PREFIX_STEPS},`,
          '      "firstStepBits": [',
          ...firstSteps,
          "      ],",
          // One number standing in for eight million floats.
          `      "hash": ${hashKvCacheTrace(id)}`,
          `    }${comma}`,
        );
      });
      return lines;
    },
  },
];

/** Decode steps whose full weight vectors are committed bit for bit. */
const KV_CACHE_PREFIX_STEPS = 10;

function main(): void {
  for (const domain of DOMAINS) {
    const lines: string[] = [
      "{",
      `  "domain": ${JSON.stringify(domain.name)},`,
      `  "events": ${PREFIX_LENGTH},`,
      `  "note": ${JSON.stringify(NOTE)},`,
      '  "traces": {',
      ...domain.entries(),
      "  }",
      "}",
      "",
    ];

    const target = new URL(
      `../src/domains/${domain.name}/trace-prefix.json`,
      import.meta.url,
    );
    writeFileSync(target, lines.join("\n"));

    console.log(
      `wrote ${domain.name}/trace-prefix.json — ${domain.ids.length} traces ` +
        `x up to ${PREFIX_LENGTH.toLocaleString()} events`,
    );
  }
}

main();
