"""Domain interfaces, trace generators and policies.

One subpackage per decision problem. The public import path drops this level —
``from policybook.cache import Sieve`` — via aliases generated by the assembly
step.
"""
