/**
 * Decision parity — the committed record of every cache policy's decisions.
 *
 * The shared vectors pin small hand-authored scenarios, and the trace-prefix
 * files pin the generators, but neither replays a policy's *decisions* over a
 * whole trace across languages. That gap is exactly where the 2Q/S3-FIFO ghost
 * divergence lived: three ports, all green, disagreeing on every canonical
 * trace. This script drives each TypeScript cache policy over the canonical
 * traces plus two deliberately churny small-cache streams — the regime where
 * ghost bugs surface and the canonical traces stay silent — and records an
 * FNV-1a64 hash of the full decision stream. The Python and C suites recompute
 * the same hashes with their own ports and compare.
 *
 * Protocol, identical in all three languages: for each event, mix one outcome
 * byte (1 hit, 0 miss inserted, 2 miss rejected by admit); after each
 * eviction, mix the victim key as four little-endian bytes.
 *
 * Regenerate with: pnpm tsx scripts/gen-decision-parity.ts
 */

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { join } from "node:path";

import { CACHE_TRACES, generateCacheTrace } from "../packages/core/src/domains/cache";
import { discoverPolicies, findRepoRoot, loadFactory } from "../packages/vectors/src/discover";
import {
  CHURN_STREAMS,
  driveCachePolicy,
  generateChurnStream,
} from "../packages/core/src/domains/cache/decision-parity";
import type { DecisionRecord } from "../packages/core/src/domains/cache/decision-parity";

async function main(): Promise<void> {
  const repoRoot = findRepoRoot();
  const policies = discoverPolicies(repoRoot).filter((policy) => policy.domain === "cache");

  const record: Record<string, Record<string, DecisionRecord>> = {};

  for (const policy of policies.slice().sort((a, b) => a.id.localeCompare(b.id))) {
    const factory = await loadFactory(policy.entry);
    const wantsFuture = policy.meta.params.some((param) => param.name === "future");
    const perTrace: Record<string, DecisionRecord> = {};

    for (const traceId of Object.keys(CACHE_TRACES)) {
      const spec = CACHE_TRACES[traceId]!;
      const trace = generateCacheTrace(traceId);
      const params: Record<string, unknown> = { capacity: spec.capacity };
      if (wantsFuture) params["future"] = Array.from(trace);
      const driven = factory(params as never, undefined as never);
      perTrace[traceId] = driveCachePolicy(driven as never, trace, spec.capacity, spec.keyUniverse);
    }

    for (const stream of CHURN_STREAMS) {
      const trace = generateChurnStream(stream);
      const params: Record<string, unknown> = { capacity: stream.capacity };
      if (wantsFuture) params["future"] = Array.from(trace);
      const driven = factory(params as never, undefined as never);
      perTrace[stream.id] = driveCachePolicy(
        driven as never,
        trace,
        stream.capacity,
        stream.keyUniverse,
      );
    }

    record[policy.id] = perTrace;
  }

  const artifact = {
    note:
      "GENERATED by scripts/gen-decision-parity.ts — do not edit. " +
      "Per-policy FNV-1a64 hashes over the full decision stream (outcome byte per " +
      "event, victim keys as 4 LE bytes). The Python and C suites recompute these " +
      "with their own ports; a mismatch means the languages no longer make the " +
      "same decisions.",
    policies: record,
  };

  const artifactPath = join(
    repoRoot,
    "packages/core/src/domains/cache/decision-parity.json",
  );
  const body = `${JSON.stringify(artifact, null, 2)}\n`;
  const previous = existsSync(artifactPath) ? readFileSync(artifactPath, "utf8") : null;
  writeFileSync(artifactPath, body);

  // The C side gets the same numbers as a compiled header, because the C tests
  // parse nothing at runtime. Policies without a C port (cache/opt) stay out.
  const C_POLICIES = new Set([
    "cache/2q",
    "cache/arc",
    "cache/clock",
    "cache/fifo",
    "cache/lfu",
    "cache/lru",
    "cache/s3-fifo",
    "cache/sieve",
    "cache/w-tinylfu",
  ]);
  const rows: string[] = [];
  for (const [policyId, perTrace] of Object.entries(record)) {
    if (!C_POLICIES.has(policyId)) continue;
    for (const [traceId, entry] of Object.entries(perTrace)) {
      rows.push(
        `    { "${policyId}", "${traceId}", UINT64_C(0x${entry.hash}), ` +
          `UINT64_C(${entry.hits}), UINT64_C(${entry.evictions}), UINT64_C(${entry.rejections}) },`,
      );
    }
  }
  const header = [
    "/* GENERATED by scripts/gen-decision-parity.ts — do not edit.",
    " *",
    " * Expected decision-stream hashes for the C cache policies. See",
    " * packages/core/src/domains/cache/decision-parity.json for the protocol.",
    " */",
    "",
    "#ifndef PB_DECISION_PARITY_EXPECTED_H",
    "#define PB_DECISION_PARITY_EXPECTED_H",
    "",
    "#include <stdint.h>",
    "",
    "typedef struct pb_decision_parity_case {",
    "    const char *policy;",
    "    const char *trace;",
    "    uint64_t hash;",
    "    uint64_t hits;",
    "    uint64_t evictions;",
    "    uint64_t rejections;",
    "} pb_decision_parity_case;",
    "",
    "static const pb_decision_parity_case PB_DECISION_PARITY[] = {",
    ...rows,
    "};",
    "",
    "#define PB_DECISION_PARITY_COUNT (sizeof(PB_DECISION_PARITY) / sizeof(PB_DECISION_PARITY[0]))",
    "",
    "#endif /* PB_DECISION_PARITY_EXPECTED_H */",
    "",
  ].join("\n");
  writeFileSync(join(repoRoot, "packages/c/tests/gen/decision_parity_expected.h"), header);

  const changed = previous !== body;
  console.log(
    `gen:decision-parity — ${Object.keys(record).length} policies, ` +
      `${changed ? "artifact updated" : "artifact unchanged"}.`,
  );
}

main().catch((error: unknown) => {
  console.error(error);
  process.exitCode = 1;
});
