# GENERATED by scripts/assemble-c.ts — do not edit.
#
# Policy implementations, assembled from policies/**/policy.c.

list(APPEND PB_POLICY_SOURCES
    src/cache/2q.c
    src/cache/arc.c
    src/cache/clock.c
    src/cache/fifo.c
    src/cache/lfu.c
    src/cache/lru.c
    src/cache/s3_fifo.c
    src/cache/sieve.c
    src/cache/w_tinylfu.c
    src/kv_cache/h2o.c
    src/kv_cache/pyramidkv.c
    src/kv_cache/scissorhands.c
    src/kv_cache/sliding_window.c
    src/kv_cache/snapkv.c
    src/kv_cache/streaming_llm.c
    src/kv_cache/tova.c
    src/rate_limiter/dual_bucket.c
    src/rate_limiter/fixed_window.c
    src/rate_limiter/gcra.c
    src/rate_limiter/leaky_bucket.c
    src/rate_limiter/sliding_counter.c
    src/rate_limiter/sliding_log.c
    src/rate_limiter/token_bucket.c
    src/retry/constant.c
    src/retry/decorrelated_jitter.c
    src/retry/equal_jitter.c
    src/retry/exponential.c
    src/retry/exponential_full_jitter.c
    src/retry/retry_after_aware.c
)
