"""The Python Rng must reproduce the reference vectors exactly.

This is the test that makes "same seed, same stream, every language" true rather
than aspirational. The vectors are generated by the TypeScript implementation
(``packages/core/scripts/gen-rng-vectors.ts``); nothing here regenerates them.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import pytest

from policybook.rng import Rng, mix32

TWO_POW_32 = 4294967296


@pytest.fixture(scope="session")
def vectors(repo_root: Path) -> dict[str, Any]:
    path = repo_root / "packages" / "core" / "src" / "rng.vectors.json"
    return json.loads(path.read_text(encoding="utf-8"))


def test_vectors_file_describes_this_generator(vectors: dict[str, Any]) -> None:
    assert vectors["generator"] == "xoshiro128** seeded by splitmix32"
    assert vectors["seeds"], "the vectors file has no seeds"


def test_next_u32_matches_reference(vectors: dict[str, Any]) -> None:
    for entry in vectors["seeds"]:
        rng = Rng(entry["seed"])
        actual = [rng.next_u32() for _ in entry["nextU32"]]
        assert actual == entry["nextU32"], f"seed {entry['seed']}"


def test_next_float_matches_reference(vectors: dict[str, Any]) -> None:
    for entry in vectors["seeds"]:
        rng = Rng(entry["seed"])
        # The reference stores the shortest decimal that round-trips; parsing it
        # recovers the identical double, so this is an exact comparison.
        expected = [float(text) for text in entry["nextFloat"]]
        actual = [rng.next_float() for _ in expected]
        assert actual == expected, f"seed {entry['seed']}"


def test_next_int_matches_reference(vectors: dict[str, Any]) -> None:
    for entry in vectors["seeds"]:
        for case in entry["nextInt"]:
            rng = Rng(entry["seed"])
            actual = [rng.next_int(case["bound"]) for _ in case["values"]]
            assert actual == case["values"], f"seed {entry['seed']} bound {case['bound']}"


def test_mix32_matches_reference(vectors: dict[str, Any]) -> None:
    for pair in vectors["mix32"]:
        assert mix32(pair["input"]) == pair["output"], f"mix32({pair['input']})"


def test_same_seed_gives_same_stream() -> None:
    left, right = Rng(42), Rng(42)
    assert [left.next_u32() for _ in range(1000)] == [right.next_u32() for _ in range(1000)]


def test_different_seeds_diverge() -> None:
    left, right = Rng(1), Rng(2)
    assert [left.next_u32() for _ in range(64)] != [right.next_u32() for _ in range(64)]


def test_seed_zero_is_not_degenerate() -> None:
    rng = Rng(0)
    values = {rng.next_u32() for _ in range(1000)}
    assert len(values) > 990


def test_next_u32_stays_in_range() -> None:
    rng = Rng(7)
    for _ in range(10_000):
        value = rng.next_u32()
        assert 0 <= value < TWO_POW_32


def test_next_float_stays_in_range() -> None:
    rng = Rng(9)
    for _ in range(10_000):
        assert 0.0 <= rng.next_float() < 1.0


def test_next_int_stays_in_range() -> None:
    rng = Rng(11)
    for bound in (2, 3, 7, 100, 65_537):
        for _ in range(2000):
            assert 0 <= rng.next_int(bound) < bound


def test_next_int_rejects_a_bad_bound() -> None:
    rng = Rng(1)
    for bad in (0, -5, TWO_POW_32 + 1):
        with pytest.raises(ValueError, match="bound must be an integer"):
            rng.next_int(bad)
    # True is an int in Python, but it is not a bound.
    with pytest.raises(ValueError, match="bound must be an integer"):
        rng.next_int(True)


def test_next_int_of_one_is_always_zero() -> None:
    rng = Rng(3)
    assert all(rng.next_int(1) == 0 for _ in range(100))


def test_distribution_is_even() -> None:
    rng = Rng(2025)
    bound, draws = 7, 70_000
    counts = [0] * bound
    for _ in range(draws):
        counts[rng.next_int(bound)] += 1
    expected = draws / bound
    assert all(expected * 0.95 < count < expected * 1.05 for count in counts)


def test_float_mean_is_near_half() -> None:
    rng = Rng(2024)
    total = sum(rng.next_float() for _ in range(100_000))
    assert 0.49 < total / 100_000 < 0.51
