"""The Python trace generators must match the TypeScript ones event for event.

This is what makes Python benchmark numbers comparable with the canonical
TypeScript ones. The reference prefixes are generated by
``packages/core/scripts/dump-trace-prefix.ts`` and committed; nothing here
regenerates them.

A divergence is almost never subtle in its cause — a port that consumes two
random draws per sample instead of one, or sums the Zipf weights in a different
order, will match for a while and then split. The tests report the first index
that differs, which is usually enough to identify which of those it was.
"""

from __future__ import annotations

import json
import math
import struct
from pathlib import Path
from typing import Any

import pytest
from _repo import find_repo_root

from policybook.domains.cache.traces import CACHE_TRACES, generate_cache_trace
from policybook.domains.kv_cache.traces import (
    KV_CACHE_TRACES,
    float32_bits,
    fround,
    generate_kv_cache_trace,
    hash_kv_cache_trace,
)
from policybook.domains.rate_limiter.traces import (
    RATE_LIMITER_TRACES,
    generate_rate_limiter_trace,
)
from policybook.domains.retry.traces import RETRY_TRACES, generate_retry_trace
from policybook.metrics import round6
from policybook.zipf import ZipfSampler, zipf_weight

REPO_ROOT = find_repo_root(Path(__file__).parent)
DOMAINS_ROOT = REPO_ROOT / "packages" / "core" / "src" / "domains"


def _reference(domain: str) -> dict[str, Any]:
    path = DOMAINS_ROOT / domain / "trace-prefix.json"
    return json.loads(path.read_text(encoding="utf-8"))


def _first_difference(actual: list[int], expected: list[int]) -> int:
    return next(i for i, (a, b) in enumerate(zip(actual, expected, strict=True)) if a != b)


@pytest.fixture(scope="session")
def cache_reference() -> dict[str, Any]:
    return _reference("cache")


@pytest.fixture(scope="session")
def rate_limiter_reference() -> dict[str, Any]:
    return _reference("rate-limiter")


@pytest.fixture(scope="session")
def retry_reference() -> dict[str, Any]:
    return _reference("retry")


@pytest.fixture(scope="session")
def kv_cache_reference() -> dict[str, Any]:
    return _reference("kv-cache")


# --- cache ------------------------------------------------------------------


def test_cache_reference_covers_every_trace(cache_reference: dict[str, Any]) -> None:
    assert cache_reference["domain"] == "cache"
    assert set(cache_reference["traces"]) == set(CACHE_TRACES)


@pytest.mark.parametrize("trace_id", sorted(CACHE_TRACES))
def test_cache_trace_matches_the_reference(
    trace_id: str, cache_reference: dict[str, Any]
) -> None:
    expected: list[int] = cache_reference["traces"][trace_id]
    actual = generate_cache_trace(trace_id, len(expected))

    assert len(actual) == len(expected)
    if actual != expected:
        first = _first_difference(actual, expected)
        pytest.fail(
            f"{trace_id} diverges from the TypeScript generator at event {first}: "
            f"got {actual[first]}, expected {expected[first]}. "
            f"Context: got {actual[max(0, first - 3):first + 3]}, "
            f"expected {expected[max(0, first - 3):first + 3]}"
        )


@pytest.mark.parametrize("trace_id", sorted(CACHE_TRACES))
def test_cache_trace_stays_in_its_key_universe(trace_id: str) -> None:
    spec = CACHE_TRACES[trace_id]
    trace = generate_cache_trace(trace_id, 10_000)
    assert all(0 <= key < spec.key_universe for key in trace)


def test_unknown_cache_trace_is_named() -> None:
    with pytest.raises(KeyError, match="unknown cache trace"):
        generate_cache_trace("nope")


def test_cache_truncation_is_a_prefix() -> None:
    full = generate_cache_trace("zipf-1.0-100k", 500)
    short = generate_cache_trace("zipf-1.0-100k", 100)
    assert short == full[:100]


# --- rate-limiter -----------------------------------------------------------


def test_rate_limiter_reference_covers_every_trace(
    rate_limiter_reference: dict[str, Any],
) -> None:
    assert rate_limiter_reference["domain"] == "rate-limiter"
    assert set(rate_limiter_reference["traces"]) == set(RATE_LIMITER_TRACES)


@pytest.mark.parametrize("trace_id", sorted(RATE_LIMITER_TRACES))
def test_rate_limiter_trace_matches_the_reference(
    trace_id: str, rate_limiter_reference: dict[str, Any]
) -> None:
    reference = rate_limiter_reference["traces"][trace_id]
    expected_times: list[int] = reference["times"]
    expected_keys: list[int] = reference["keys"]
    actual = generate_rate_limiter_trace(trace_id, len(expected_times))

    assert len(actual.times) == len(expected_times)
    assert len(actual.keys) == len(expected_keys)

    if actual.times != expected_times:
        first = _first_difference(actual.times, expected_times)
        pytest.fail(
            f"{trace_id} arrival times diverge at event {first}: "
            f"got {actual.times[first]} ms, expected {expected_times[first]} ms. "
            f"Context: got {actual.times[max(0, first - 3):first + 3]}, "
            f"expected {expected_times[max(0, first - 3):first + 3]}"
        )
    if actual.keys != expected_keys:
        first = _first_difference(actual.keys, expected_keys)
        pytest.fail(
            f"{trace_id} keys diverge at event {first} (time "
            f"{actual.times[first]} ms): got {actual.keys[first]}, "
            f"expected {expected_keys[first]}"
        )


@pytest.mark.parametrize("trace_id", sorted(RATE_LIMITER_TRACES))
def test_rate_limiter_trace_is_ordered_and_bounded(trace_id: str) -> None:
    spec = RATE_LIMITER_TRACES[trace_id]
    trace = generate_rate_limiter_trace(trace_id, 5_000)

    assert all(0 <= key < spec.key_universe for key in trace.keys)
    assert all(t < spec.duration_ms for t in trace.times)
    # One Bernoulli trial per millisecond means arrival times are strictly
    # increasing, not merely non-decreasing.
    assert all(a < b for a, b in zip(trace.times, trace.times[1:], strict=False))


def test_bursty_arrives_only_during_an_on_phase() -> None:
    trace = generate_rate_limiter_trace("bursty")
    assert all(t % 2_000 < 200 for t in trace.times)


def test_unknown_rate_limiter_trace_is_named() -> None:
    with pytest.raises(KeyError, match="unknown rate-limiter trace"):
        generate_rate_limiter_trace("nope")


def test_rate_limiter_truncation_is_a_prefix() -> None:
    full = generate_rate_limiter_trace("many-keys", 500)
    short = generate_rate_limiter_trace("many-keys", 100)
    assert short.times == full.times[:100]
    assert short.keys == full.keys[:100]


# --- retry ------------------------------------------------------------------


def test_retry_reference_covers_every_trace(retry_reference: dict[str, Any]) -> None:
    assert retry_reference["domain"] == "retry"
    assert set(retry_reference["traces"]) == set(RETRY_TRACES)


@pytest.mark.parametrize("trace_id", sorted(RETRY_TRACES))
def test_retry_outages_match_the_reference(
    trace_id: str, retry_reference: dict[str, Any]
) -> None:
    # A retry episode's identity is a single draw — how long the outage lasts —
    # and it is the first draw of that episode's environment stream, so it is
    # exactly what the harness sees. If the Rng or its per-episode seeding
    # differed, these numbers would differ first.
    expected: list[int] = retry_reference["traces"][trace_id]
    actual = generate_retry_trace(trace_id, len(expected))

    assert len(actual) == len(expected)
    if actual != expected:
        first = _first_difference(actual, expected)
        pytest.fail(
            f"{trace_id} diverges from the TypeScript generator at episode {first}: "
            f"got an outage of {actual[first]} ms, expected {expected[first]} ms"
        )


@pytest.mark.parametrize("trace_id", sorted(RETRY_TRACES))
def test_retry_outages_stay_inside_their_bound(trace_id: str) -> None:
    spec = RETRY_TRACES[trace_id]
    assert all(0 <= outage < spec.max_outage_ms for outage in generate_retry_trace(trace_id))


def test_retry_streams_never_collide() -> None:
    # The environment and policy streams are separate so a policy's own draws
    # cannot shift the environment's coin flips. That only holds if no seed is
    # ever shared between them.
    from policybook.domains.retry.traces import environment_seed, policy_seed

    spec = RETRY_TRACES["outage-30s"]
    seeds = {environment_seed(spec, e) for e in range(spec.episodes)}
    seeds |= {policy_seed(spec, e) for e in range(spec.episodes)}
    assert len(seeds) == spec.episodes * 2


def test_unknown_retry_trace_is_named() -> None:
    with pytest.raises(KeyError, match="unknown retry trace"):
        generate_retry_trace("nope")


# --- kv-cache ---------------------------------------------------------------
#
# The only domain whose trace is floating-point, and so the only one where
# parity is checked on bit patterns rather than values. Two floats that print
# alike can differ in the last place, and a single differing ULP propagates
# through the normalisation into every other weight of that step.


def test_kv_cache_reference_covers_every_trace(kv_cache_reference: dict[str, Any]) -> None:
    assert kv_cache_reference["domain"] == "kv-cache"
    assert set(kv_cache_reference["traces"]) == set(KV_CACHE_TRACES)


@pytest.mark.parametrize("trace_id", sorted(KV_CACHE_TRACES))
def test_kv_cache_first_steps_match_bit_for_bit(
    trace_id: str, kv_cache_reference: dict[str, Any]
) -> None:
    reference = kv_cache_reference["traces"][trace_id]
    expected_steps: list[list[int]] = reference["firstStepBits"]

    actual_steps = list(generate_kv_cache_trace(trace_id, len(expected_steps)))
    assert len(actual_steps) == len(expected_steps)

    for step_index, (actual, expected) in enumerate(
        zip(actual_steps, expected_steps, strict=True)
    ):
        step = step_index + 1
        assert len(actual) == step, f"step {step} should hold {step} weights"

        actual_bits = [float32_bits(weight) for weight in actual]
        if actual_bits != expected:
            first = _first_difference(actual_bits, expected)
            pytest.fail(
                f"{trace_id} diverges from the TypeScript generator at step {step}, "
                f"position {first}: got bits {actual_bits[first]:#010x}, "
                f"expected {expected[first]:#010x}"
            )


@pytest.mark.parametrize("trace_id", sorted(KV_CACHE_TRACES))
def test_kv_cache_whole_trace_hashes_the_same(
    trace_id: str, kv_cache_reference: dict[str, Any]
) -> None:
    # The committed first steps say *where* a divergence starts; this says
    # whether one happens at all, over all 4,095 steps rather than the first ten.
    expected: int = kv_cache_reference["traces"][trace_id]["hash"]
    assert hash_kv_cache_trace(trace_id) == expected


@pytest.mark.parametrize("trace_id", sorted(KV_CACHE_TRACES))
def test_kv_cache_steps_stop_one_short_of_the_sequence(trace_id: str) -> None:
    # Position 0's token exists before decoding starts and never attends, so an
    # N-token sequence has N-1 decode steps.
    spec = KV_CACHE_TRACES[trace_id]
    steps = sum(1 for _ in generate_kv_cache_trace(trace_id))
    assert steps == spec.sequence_length - 1


@pytest.mark.parametrize("trace_id", sorted(KV_CACHE_TRACES))
def test_kv_cache_weights_are_exactly_float32(trace_id: str) -> None:
    # TypeScript yields a Float32Array and C a `float *`, so both are float32 by
    # construction. Python has no float32, so its generator rounds explicitly —
    # and nothing else here would notice if it stopped. The bit-pattern
    # comparison cannot: `float32_bits` packs to float32 itself, so it returns
    # the same bits whether or not the value was already rounded. Without this
    # check a Python policy would be handed float64 weights that its TypeScript
    # and C counterparts never see.
    #
    # The round trip is spelled out here rather than borrowing the module's own
    # `fround`: a test that validates a function by calling it would pass no
    # matter what that function did.
    round_trip = struct.Struct("<f")

    for step in generate_kv_cache_trace(trace_id, 200):
        for weight in step:
            assert round_trip.unpack(round_trip.pack(weight))[0] == weight


def test_kv_cache_weights_sum_to_one() -> None:
    for step in generate_kv_cache_trace("decode-4096", 300):
        # Float32 weights summed in float64: a few ULPs of the largest term.
        assert abs(math.fsum(step) - 1.0) < 1e-6


def test_kv_cache_never_emits_a_zero_weight() -> None:
    # The noise component exists precisely so a policy cannot identify the
    # structure by testing for zero.
    for step in generate_kv_cache_trace("decode-4096", 200):
        assert all(weight > 0.0 for weight in step)


def test_kv_cache_truncation_is_a_prefix() -> None:
    short = [list(step) for step in generate_kv_cache_trace("decode-4096", 20)]
    full = [list(step) for step in generate_kv_cache_trace("decode-4096", 60)]
    assert short == full[:20]


def test_unknown_kv_cache_trace_is_named() -> None:
    with pytest.raises(KeyError, match="unknown kv-cache trace"):
        list(generate_kv_cache_trace("nope"))


def test_fround_rounds_to_nearest_even_like_math_fround() -> None:
    # Python has no float32, so every weight makes a round trip through four
    # bytes. If struct rounded differently from JavaScript's Math.fround or C's
    # (float) cast, every weight in the trace would be off by an ULP.
    assert fround(1.0) == 1.0
    assert fround(0.1) == 0.10000000149011612

    # Above 1.0 the float32 step is 2**-23, so 1 + 2**-24 sits exactly halfway
    # between 1.0 and the next representable value. These two cases are the
    # point: both are exact ties, and they resolve in *opposite* directions,
    # towards whichever neighbour has an even mantissa. Truncation would take
    # both down; ties-away-from-zero would take both up.
    ulp = 2.0**-23
    assert fround(1.0 + ulp / 2) == 1.0
    assert fround(1.0 + ulp + ulp / 2) == 1.0 + 2 * ulp

    # And an exactly representable value survives untouched.
    assert fround(1.0 + ulp) == 1.0 + ulp


# --- shared machinery -------------------------------------------------------


def test_zipf_weight_matches_pow_without_using_it() -> None:
    # The sqrt formulation has to agree with pow to within rounding — that is
    # what makes it a legitimate substitution rather than a different
    # distribution. It is used instead of pow because pow is not correctly
    # rounded across C standard libraries.
    for rank in (0, 1, 2, 3, 9, 99, 9_999):
        assert abs(zipf_weight(rank, 0.75) - (rank + 1) ** -0.75) < 1e-15
        assert zipf_weight(rank, 1.0) == 1 / (rank + 1)


def test_zipf_sampler_rejects_bad_arguments() -> None:
    with pytest.raises(ValueError, match="positive integer"):
        ZipfSampler(0, 1.0)
    with pytest.raises(ValueError, match="alpha must be"):
        ZipfSampler(10, 0.5)


def test_round6_is_half_up_not_bankers() -> None:
    # The registry's reference implementation is JavaScript, whose Math.round is
    # half-up. Python's built-in round is half-to-even and disagrees on ties,
    # which would put Python benchmark rows one ULP off the committed ones.
    assert round6(0.0000005) == 0.000001
    assert round(0.0000005, 6) == 0.0
    assert round6(0.9123455) == 0.912346
    assert round6(1 / 3) == 0.333333
