"""What the distribution promises, checked rather than asserted.

Three claims on the package page are the kind that rot silently: that it has no
dependencies, that the version agrees with the rest of the repository, and that
every domain is importable by the path the documentation gives. A wheel that
broke any of them would still install and still pass every other test here.
"""

from __future__ import annotations

import ast
import sys
from pathlib import Path

import pytest
import tomllib
from _repo import find_repo_root

import policybook

REPO_ROOT = find_repo_root(Path(__file__).parent)
PACKAGE_ROOT = REPO_ROOT / "packages" / "python"
SOURCE_ROOT = PACKAGE_ROOT / "policybook"


def _pyproject() -> dict[str, object]:
    with (PACKAGE_ROOT / "pyproject.toml").open("rb") as handle:
        return tomllib.load(handle)


def test_version_agrees_with_pyproject() -> None:
    project = _pyproject()["project"]
    assert isinstance(project, dict)
    assert policybook.__version__ == project["version"]


def test_version_is_an_alpha_of_the_core_version() -> None:
    # The three implementations ship as one release, so a Python wheel claiming
    # a version the TypeScript core has never heard of would be lying about
    # which vectors it satisfies.
    core = (REPO_ROOT / "packages" / "core" / "src" / "index.ts").read_text(encoding="utf-8")
    marker = 'export const CORE_VERSION = "'
    start = core.index(marker) + len(marker)
    core_version = core[start : core.index('"', start)]

    assert policybook.__version__.startswith(core_version), (
        f"python {policybook.__version__} and core {core_version} have diverged"
    )


def test_the_package_declares_no_dependencies() -> None:
    project = _pyproject()["project"]
    assert isinstance(project, dict)
    assert project["dependencies"] == []


def test_nothing_imports_outside_the_standard_library() -> None:
    """The stdlib-only claim, checked by reading every import in the package.

    Declaring no dependencies in `pyproject.toml` is not the same as having
    none: an import of something already installed in the developer's
    environment would pass every test here and fail on a user's machine. This
    walks the sources instead.
    """
    allowed = set(sys.stdlib_module_names) | {"policybook"}
    offenders: list[str] = []

    for path in sorted(SOURCE_ROOT.rglob("*.py")):
        tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
        for node in ast.walk(tree):
            if isinstance(node, ast.Import):
                roots = [alias.name.split(".")[0] for alias in node.names]
            elif isinstance(node, ast.ImportFrom):
                # A relative import stays inside the package by definition.
                if node.level > 0 or node.module is None:
                    continue
                roots = [node.module.split(".")[0]]
            else:
                continue

            for root in roots:
                if root not in allowed:
                    offenders.append(f"{path.relative_to(REPO_ROOT)}: {root}")

    assert offenders == [], "third-party imports found: " + ", ".join(offenders)


def test_py_typed_is_shipped() -> None:
    # Without this marker every type in the package is invisible to a user's
    # type checker, and the "typed" classifier is false advertising.
    assert (SOURCE_ROOT / "py.typed").is_file()


@pytest.mark.parametrize(
    ("module", "policy"),
    [
        ("policybook.cache", "Sieve"),
        ("policybook.rate_limiter", "TokenBucket"),
        ("policybook.retry", "ExponentialFullJitter"),
        ("policybook.kv_cache", "StreamingLlm"),
    ],
)
def test_every_domain_is_importable_by_its_documented_path(module: str, policy: str) -> None:
    # The paths the README and the package docstring give. They are generated by
    # scripts/assemble-python.ts, so a change to the assembler that renamed one
    # would otherwise only be noticed by a reader.
    imported = __import__(module, fromlist=[policy])
    assert hasattr(imported, policy), f"{module} does not export {policy}"


def test_a_policy_from_each_domain_actually_runs() -> None:
    # Importable is not usable. One decision from each domain, through the
    # public path, with no test-only scaffolding.
    from policybook.cache import Sieve
    from policybook.kv_cache import StreamingLlm
    from policybook.rate_limiter import TokenBucket
    from policybook.retry import ExponentialFullJitter

    cache = Sieve(capacity=3)
    cache.on_access("a", hit=False)
    assert cache.size() == 1

    limiter = TokenBucket(rate_per_sec=10, burst=1)
    assert limiter.allow(1, 1, 0) is True

    backoff = ExponentialFullJitter(base_ms=100, cap_ms=1000, max_attempts=3)
    assert backoff.next_delay(1, {"status": 503, "retryable": True}) is not None

    kv = StreamingLlm(budget=4, sinks=2)
    kv.on_decode_step(1, [1.0])
    assert kv.kept_count() == 2
