/**
 * The site cannot disagree with its own benchmark tables.
 *
 * This is the guarantee behind every number on the site. The
 * runner reimplements the harness loops — it has to, because a runner stops
 * between events and `runCacheTrace` does not — and `simulation.test.ts` proves
 * those loops match the harness. This goes one step further and compares the
 * runner against the **committed `bench.json` files**: the numbers actually
 * printed in the tables, generated by a separate script, on a different day.
 *
 * The distinction matters. A runner that agreed with the live harness but not
 * with the committed files would put a policy page's table and its runner in
 * contradiction, and a reader who noticed would be right to distrust both. So
 * the assertion is exact equality, at full trace length, with no tolerance:
 * these are deterministic integer-seeded simulations, and "close" would mean
 * something had drifted.
 *
 * One trace per domain, because the point is to catch drift in the *plumbing* —
 * a metric wired up wrongly, a trace generated differently, a parameter lost in
 * translation — and that shows up on the first trace as readily as the tenth.
 */

import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { CACHE_TRACES } from "../../../../packages/core/src/domains/cache";
import { RATE_LIMITER_TRACES } from "../../../../packages/core/src/domains/rate-limiter";
import { KV_CACHE_TRACES } from "../../../../packages/core/src/domains/kv-cache";
import Lru from "../../../../policies/cache/lru/index";
import Sieve from "../../../../policies/cache/sieve/index";
import TokenBucket from "../../../../policies/rate-limiter/token-bucket/index";
import H2o from "../../../../policies/kv-cache/h2o/index";
import { createSimulation } from "./simulation";

const ROOT = join(process.cwd(), "policies");

interface BenchFile {
  policy: string;
  traces: Record<string, { metrics: Record<string, number> }>;
}

/** The committed numbers for a policy, read from the file the tables render. */
function committed(id: string, trace: string): Record<string, number> {
  const file = JSON.parse(
    readFileSync(join(ROOT, id, "bench.json"), "utf8"),
  ) as BenchFile;

  const row = file.traces[trace];
  if (row === undefined) {
    throw new Error(
      `${id}/bench.json has no trace "${trace}". Has: ${Object.keys(file.traces).join(", ")}`,
    );
  }
  return row.metrics;
}

/** Run the site's own harness to the end of a full-length trace. */
function siteMetrics(
  domain: string,
  Policy: new (params: never) => unknown,
  params: Record<string, unknown>,
  trace: string,
  length: number,
): Record<string, number> {
  const simulation = createSimulation(
    domain,
    (p) => new Policy(p as never),
    params,
    trace,
    length,
  );
  simulation.seek(simulation.totalSteps);
  return simulation.frame().metrics;
}

describe("the site agrees with the committed benchmarks", () => {
  it("matches cache/sieve on the full zipf trace", () => {
    const spec = CACHE_TRACES["zipf-1.0-100k"]!;
    const expected = committed("cache/sieve", "zipf-1.0-100k");
    const actual = siteMetrics(
      "cache",
      Sieve as never,
      { capacity: spec.capacity },
      "zipf-1.0-100k",
      spec.events,
    );

    for (const [name, value] of Object.entries(expected)) {
      expect(actual[name], name).toBe(value);
    }
  });

  it("matches cache/lru too, so one policy is not carrying the result", () => {
    // Two policies rather than one: a plumbing fault that happened to produce
    // SIEVE's committed number would be a remarkable coincidence, but a shared
    // constant read from the wrong place could do it.
    const spec = CACHE_TRACES["zipf-1.0-100k"]!;
    const expected = committed("cache/lru", "zipf-1.0-100k");
    const actual = siteMetrics(
      "cache",
      Lru as never,
      { capacity: spec.capacity },
      "zipf-1.0-100k",
      spec.events,
    );

    for (const [name, value] of Object.entries(expected)) {
      expect(actual[name], name).toBe(value);
    }
  });

  it("matches rate-limiter/token-bucket on the bursty trace", () => {
    // The bench parameters, from `scripts/bench.ts`. A limiter benched at
    // different settings from the ones the runner uses would produce two
    // different truths on the same page.
    const expected = committed("rate-limiter/token-bucket", "bursty");
    const actual = siteMetrics(
      "rate-limiter",
      TokenBucket as never,
      { ratePerSec: 100, burst: 100 },
      "bursty",
      // At most one arrival per millisecond, so the trace's duration is an
      // upper bound on its event count and this asks for all of it.
      RATE_LIMITER_TRACES["bursty"]!.durationMs,
    );

    for (const [name, value] of Object.entries(expected)) {
      expect(actual[name], name).toBe(value);
    }
  });

  it("matches kv-cache/h2o at the reference budget", () => {
    // The bench keys this domain as `<trace>@<budget>`, because the ranking
    // genuinely changes with the budget.
    const spec = KV_CACHE_TRACES["decode-4096"]!;
    const expected = committed("kv-cache/h2o", "decode-4096@512");
    const actual = siteMetrics(
      "kv-cache",
      H2o as never,
      { budget: 512 },
      "decode-4096",
      spec.sequenceLength,
    );

    for (const [name, value] of Object.entries(expected)) {
      expect(actual[name], name).toBe(value);
    }
  });

  it("compares something, rather than passing on an empty set of metrics", () => {
    /*
     * The failure mode this exists for.
     *
     * Every assertion above loops over the *expected* object. Were `committed`
     * to return `{}` — a renamed field, a restructured file, a trace key that
     * quietly stopped matching — the loop would run zero times and four tests
     * would pass having compared nothing at all. This pins that there is
     * something in there.
     */
    for (const [id, trace] of [
      ["cache/sieve", "zipf-1.0-100k"],
      ["cache/lru", "zipf-1.0-100k"],
      ["rate-limiter/token-bucket", "bursty"],
      ["kv-cache/h2o", "decode-4096@512"],
    ] as const) {
      const metrics = committed(id, trace);
      expect(Object.keys(metrics).length, `${id} @ ${trace}`).toBeGreaterThanOrEqual(2);
      for (const value of Object.values(metrics)) {
        expect(Number.isFinite(value)).toBe(true);
      }
    }
  });
});
